import type { LevelDef } from './types';

// Signature mechanic: narrow single-tile ledges over open pits — one misstep
// off the edge means a fall. No new engine code needed, just narrow platforms.
export const darkSoulsLevel: LevelDef = {
  id: 'darkSouls',
  name: 'Тёмные Руины',
  theme: 'darkSouls',
  widthTiles: 58,
  heightTiles: 12,
  groundY: 10,
  playerStart: { x: 2, y: 9 },
  finish: { x: 55, y: 9 },
  musicKey: 'darkSouls',
  narrowLedgeFall: true,
  platforms: [
    { x: 0, y: 10, w: 8, h: 2 },
    { x: 9, y: 10, w: 1, h: 2 },
    { x: 11, y: 10, w: 1, h: 2 },
    { x: 13, y: 10, w: 2, h: 2 },
    { x: 16, y: 10, w: 1, h: 2 },
    { x: 18, y: 10, w: 9, h: 2 },
    { x: 22, y: 7, w: 3, h: 1 },
    { x: 29, y: 10, w: 1, h: 2 },
    { x: 31, y: 10, w: 1, h: 2 },
    { x: 33, y: 9, w: 2, h: 1, moving: { axis: 'y', range: 2, speed: 50 } },
    { x: 36, y: 10, w: 1, h: 2 },
    { x: 38, y: 10, w: 20, h: 2 },
    { x: 42, y: 7, w: 3, h: 1 },
    { x: 48, y: 6, w: 3, h: 1 },
  ],
  hazards: [
    { x: 24, y: 9, w: 1, h: 1, type: 'spikes' },
    { x: 44, y: 9, w: 1, h: 1, type: 'spikes' },
  ],
  enemies: [
    { x: 20, y: 9, type: 'skeleton', patrol: 1, speed: 70 },
    { x: 25, y: 9, type: 'slime', patrol: 1, speed: 70 },
    { x: 40, y: 9, type: 'skeleton', patrol: 1.5, speed: 75 },
    { x: 50, y: 6, type: 'drake', patrol: 3, speed: 90 },
  ],
  pickups: [
    { x: 2, y: 9, type: 'heart' },
    { x: 5, y: 9, type: 'heart' },
    { x: 10, y: 9, type: 'heart' },
    { x: 14, y: 9, type: 'heart' },
    { x: 19, y: 9, type: 'heartPurple' },
    { x: 22, y: 6, type: 'heart' },
    { x: 26, y: 9, type: 'heart' },
    { x: 30, y: 9, type: 'fireflower' },
    { x: 34, y: 8, type: 'heart' },
    { x: 39, y: 9, type: 'heartWhite' },
    { x: 42, y: 6, type: 'heart' },
    { x: 48, y: 9, type: 'heart' },
    { x: 52, y: 9, type: 'heart' },
    { x: 8, y: 9, type: 'coin' },
    { x: 53, y: 9, type: 'coin' },
    { x: 48, y: 3, type: 'coin', secret: true, requiresLevitate: true },
    { x: 49, y: 3, type: 'heartPurple', secret: true, requiresLevitate: true },
  ],
  checkpoints: [
    { x: 18, y: 9 },
    { x: 38, y: 9 },
    { x: 50, y: 9 },
  ],
};
