import type { LevelDef } from './types';

// Signature mechanic: wobbling platforms — angle sways for a claymation feel,
// while the physics body stays a stable rectangle underneath.
export const neverhoodLevel: LevelDef = {
  id: 'neverhood',
  name: 'Пластилиновый Сон',
  theme: 'neverhood',
  widthTiles: 58,
  heightTiles: 12,
  groundY: 10,
  playerStart: { x: 2, y: 9 },
  finish: { x: 55, y: 9 },
  musicKey: 'neverhood',
  platforms: [
    { x: 0, y: 10, w: 10, h: 2 },
    { x: 12, y: 9, w: 2, h: 1, wobble: true },
    { x: 16, y: 8, w: 2, h: 1, wobble: true },
    { x: 20, y: 9, w: 2, h: 1, wobble: true },
    { x: 24, y: 7, w: 2, h: 1, wobble: true },
    { x: 28, y: 8, w: 2, h: 1, wobble: true },
    { x: 33, y: 9, w: 2, h: 1, wobble: true },
    { x: 37, y: 7, w: 2, h: 1, wobble: true },
    { x: 41, y: 10, w: 17, h: 2 },
    { x: 47, y: 6, w: 3, h: 1 },
  ],
  hazards: [
    { x: 44, y: 9, w: 1, h: 1, type: 'spikes' },
  ],
  enemies: [
    { x: 4, y: 9, type: 'slime', patrol: 1, speed: 80 },
    { x: 7, y: 9, type: 'slime', patrol: 1, speed: 80 },
    { x: 44, y: 9, type: 'skeleton', patrol: 1.5, speed: 85 },
    { x: 50, y: 6, type: 'drake', patrol: 2, speed: 95 },
  ],
  pickups: [
    { x: 2, y: 9, type: 'heart' },
    { x: 5, y: 9, type: 'heart' },
    { x: 12, y: 8, type: 'heart' },
    { x: 16, y: 7, type: 'heart' },
    { x: 20, y: 8, type: 'heart' },
    { x: 21, y: 8, type: 'heartPurple' },
    { x: 24, y: 6, type: 'heart' },
    { x: 28, y: 7, type: 'heart' },
    { x: 33, y: 8, type: 'heart' },
    { x: 37, y: 6, type: 'heart' },
    { x: 41, y: 9, type: 'heartWhite' },
    { x: 44, y: 6, type: 'heart' },
    { x: 45, y: 9, type: 'fireflower' },
    { x: 8, y: 9, type: 'coin' },
    { x: 50, y: 3, type: 'coin', secret: true, requiresLevitate: true },
    { x: 51, y: 3, type: 'coin', secret: true, requiresLevitate: true },
  ],
  checkpoints: [
    { x: 21, y: 8 },
    { x: 37, y: 6 },
    { x: 48, y: 9 },
  ],
};
