import type { LevelDef } from './types';

// Hardest level: narrow ledge gauntlets like Dark Souls, but longer and with
// noticeably faster, more aggressive enemies.
export const sekiroLevel: LevelDef = {
  id: 'sekiro',
  name: 'Клинок и Сакура',
  theme: 'sekiro',
  widthTiles: 66,
  heightTiles: 12,
  groundY: 10,
  playerStart: { x: 2, y: 9 },
  finish: { x: 63, y: 9 },
  musicKey: 'sekiro',
  narrowLedgeFall: true,
  platforms: [
    { x: 0, y: 10, w: 8, h: 2 },
    { x: 9, y: 10, w: 1, h: 2 },
    { x: 11, y: 10, w: 1, h: 2 },
    { x: 13, y: 10, w: 1, h: 2 },
    { x: 15, y: 10, w: 1, h: 2 },
    { x: 17, y: 10, w: 2, h: 2 },
    { x: 19, y: 10, w: 9, h: 2 },
    { x: 29, y: 10, w: 1, h: 2 },
    { x: 31, y: 10, w: 1, h: 2 },
    { x: 33, y: 10, w: 2, h: 2 },
    { x: 36, y: 10, w: 1, h: 2 },
    { x: 38, y: 10, w: 1, h: 2 },
    { x: 40, y: 10, w: 9, h: 2 },
    { x: 50, y: 10, w: 1, h: 2 },
    { x: 52, y: 10, w: 1, h: 2 },
    { x: 54, y: 10, w: 1, h: 2 },
    { x: 56, y: 10, w: 1, h: 2 },
    { x: 58, y: 10, w: 1, h: 2 },
    { x: 60, y: 10, w: 6, h: 2 },
  ],
  hazards: [
    { x: 23, y: 9, w: 1, h: 1, type: 'spikes' },
    { x: 45, y: 9, w: 1, h: 1, type: 'spikes' },
  ],
  enemies: [
    { x: 22, y: 9, type: 'skeleton', patrol: 1.5, speed: 110 },
    { x: 25, y: 9, type: 'skeleton', patrol: 1, speed: 115 },
    { x: 42, y: 9, type: 'skeleton', patrol: 1.5, speed: 120 },
    { x: 45, y: 6, type: 'drake', patrol: 2, speed: 130 },
    { x: 62, y: 9, type: 'skeleton', patrol: 1, speed: 130 },
  ],
  pickups: [
    { x: 2, y: 9, type: 'heart' },
    { x: 5, y: 9, type: 'heart' },
    { x: 10, y: 9, type: 'heart' },
    { x: 14, y: 9, type: 'heart' },
    { x: 20, y: 9, type: 'heartWhite' },
    { x: 21, y: 9, type: 'heart' },
    { x: 26, y: 9, type: 'heart' },
    { x: 24, y: 9, type: 'fireflower' },
    { x: 34, y: 9, type: 'heart' },
    { x: 39, y: 9, type: 'heartPurple' },
    { x: 47, y: 9, type: 'heart' },
    { x: 53, y: 9, type: 'heart' },
    { x: 60, y: 9, type: 'heart' },
    { x: 8, y: 9, type: 'coin' },
    { x: 58, y: 3, type: 'coin', secret: true, requiresLevitate: true },
    { x: 59, y: 3, type: 'heartPurple', secret: true, requiresLevitate: true },
  ],
  checkpoints: [
    { x: 19, y: 9 },
    { x: 40, y: 9 },
    { x: 61, y: 9 },
  ],
};
