import type { LevelDef } from './types';

// Signature mechanic: dense enemy "waves" — same AI, just packed tighter and faster.
export const seriousSamLevel: LevelDef = {
  id: 'seriousSam',
  name: 'Пески Безумия',
  theme: 'seriousSam',
  widthTiles: 60,
  heightTiles: 12,
  groundY: 10,
  playerStart: { x: 2, y: 9 },
  finish: { x: 57, y: 9 },
  musicKey: 'seriousSam',
  platforms: [
    { x: 0, y: 10, w: 16, h: 2 },
    { x: 18, y: 10, w: 20, h: 2 },
    { x: 40, y: 10, w: 20, h: 2 },
    { x: 20, y: 7, w: 3, h: 1 },
    { x: 30, y: 6, w: 3, h: 1 },
    { x: 44, y: 7, w: 3, h: 1, moving: { axis: 'x', range: 2, speed: 60 } },
  ],
  hazards: [
    { x: 26, y: 9, w: 1, h: 1, type: 'spikes' },
    { x: 48, y: 9, w: 1, h: 1, type: 'spikes' },
  ],
  enemies: [
    { x: 6, y: 9, type: 'slime', patrol: 0.5, speed: 110 },
    { x: 8, y: 9, type: 'slime', patrol: 0.5, speed: 110 },
    { x: 10, y: 9, type: 'slime', patrol: 0.5, speed: 110 },
    { x: 22, y: 9, type: 'skeleton', patrol: 0.6, speed: 120 },
    { x: 24, y: 9, type: 'skeleton', patrol: 0.6, speed: 120 },
    { x: 26.5, y: 9, type: 'skeleton', patrol: 0.6, speed: 120 },
    { x: 42, y: 9, type: 'skeleton', patrol: 1, speed: 140 },
    { x: 46, y: 6, type: 'drake', patrol: 2, speed: 140 },
  ],
  pickups: [
    { x: 2, y: 9, type: 'heart' },
    { x: 16, y: 9, type: 'heart' },
    { x: 12, y: 9, type: 'fireflower' },
    { x: 20, y: 6, type: 'heart' },
    { x: 20, y: 9, type: 'heartWhite' },
    { x: 30, y: 5, type: 'heart' },
    { x: 34, y: 9, type: 'heart' },
    { x: 36, y: 9, type: 'heart' },
    { x: 39, y: 9, type: 'heartPurple' },
    { x: 44, y: 6, type: 'heart' },
    { x: 50, y: 9, type: 'heart' },
    { x: 52, y: 9, type: 'heart' },
    { x: 54, y: 9, type: 'heart' },
    { x: 4, y: 9, type: 'coin' },
    { x: 56, y: 9, type: 'coin' },
    { x: 51, y: 3, type: 'coin', secret: true, requiresLevitate: true },
    { x: 52, y: 3, type: 'coin', secret: true, requiresLevitate: true },
  ],
  checkpoints: [
    { x: 18, y: 9 },
    { x: 30, y: 9 },
    { x: 44, y: 9 },
  ],
};
