import type { LevelDef } from './types';

export const testLevel: LevelDef = {
  id: 'test',
  name: 'Полигон',
  theme: 'test',
  widthTiles: 54,
  heightTiles: 12,
  groundY: 10,
  playerStart: { x: 2, y: 9 },
  finish: { x: 51, y: 9 },
  musicKey: 'test',
  platforms: [
    { x: 0, y: 10, w: 10, h: 2 },
    { x: 12, y: 10, w: 8, h: 2 },
    { x: 22, y: 10, w: 12, h: 2 },
    { x: 36, y: 10, w: 18, h: 2 },
    { x: 14, y: 7, w: 3, h: 1 },
    { x: 24, y: 6, w: 3, h: 1 },
    { x: 28, y: 8, w: 2, h: 1, moving: { axis: 'x', range: 3, speed: 60 } },
    { x: 30, y: 3, w: 3, h: 1 },
  ],
  hazards: [
    { x: 18, y: 9, w: 2, h: 1, type: 'spikes' },
    { x: 38, y: 9, w: 1, h: 1, type: 'spikes' },
    { x: 46, y: 6, w: 1, h: 4, type: 'timedBarrier', onMs: 1200, offMs: 900, offsetMs: 0 },
  ],
  enemies: [
    { x: 16, y: 9, type: 'slime', patrol: 1.5, speed: 80 },
    { x: 26, y: 9, type: 'skeleton', patrol: 2, speed: 70 },
    { x: 44, y: 6, type: 'drake', patrol: 3, speed: 100 },
  ],
  pickups: [
    { x: 4, y: 9, type: 'heart' },
    { x: 6, y: 9, type: 'heart' },
    { x: 14, y: 6, type: 'heart' },
    { x: 15, y: 6, type: 'heart' },
    { x: 22, y: 9, type: 'fireflower' },
    { x: 24, y: 5, type: 'heartPurple' },
    { x: 26, y: 5, type: 'heart' },
    { x: 28, y: 7, type: 'heart' },
    { x: 32, y: 9, type: 'heart' },
    { x: 33, y: 9, type: 'heartWhite' },
    { x: 38, y: 6, type: 'heart' },
    { x: 40, y: 9, type: 'heart' },
    { x: 42, y: 9, type: 'heart' },
    { x: 48, y: 9, type: 'coin' },
    { x: 8, y: 9, type: 'coin' },
    // secret alcove, only reachable via the purple-heart double jump from the moving platform
    { x: 30, y: 2, type: 'coin', secret: true, requiresLevitate: true },
    { x: 31, y: 2, type: 'coin', secret: true, requiresLevitate: true },
    { x: 32, y: 2, type: 'heartPurple', secret: true, requiresLevitate: true },
  ],
  checkpoints: [
    { x: 12, y: 9 },
    { x: 24, y: 9 },
    { x: 40, y: 9 },
  ],
};
